#!/bin/bash

AMIAN_VERSION=1.1
AMIAN_BUILD=1.1.15

########### BEGIN CLEAN ###########
set -e
lb clean noauto "${@}"
rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
########### END CLEAN ###########


########### BEGIN CONFIG ###########
# --interactive shell \
# --apt-indices false \
# --memtest none \
# --debian-installer live \

set -e
lb config noauto \
        --memtest memtest86+ \
        --mode debian \
        --distribution buster  \
        --bootloaders syslinux \
        --architectures amd64 \
        --debian-installer false \
        --binary-images iso-hybrid  \
        --archive-areas "main contrib non-free" \
        --bootappend-live "boot=live config locales=en_US.UTF-8 keyboard-layouts=us username=user hostname=amian user-fullname=user@amian" \
        "${@}"

# Configure basic desktop packages
echo task-gnome-desktop > config/package-lists/desktop.list.chroot
echo task-english >> config/package-lists/desktop.list.chroot

# Configure repository packages
echo    "elinks git wget macchanger aircrack-ng vim inkscape gimp nmap iptraf vlc whois cryptsetup cryptmount" > config/package-lists/custom.list.chroot

###HOOK
cat > config/hooks/live/amian.hook.chroot << EOF
#!/bin/bash

set -e

systemctl enable startup.service

cd /root
git clone https://github.com/DoKiNet/DBox.git
cd DBox
./dbox install server

cd /root
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt -y install ./google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb



EOF
####END HOOK

###### BEGIN STARTUP SERVICE ######
mkdir -p config/includes.chroot/root
mkdir -p config/includes.chroot/etc/systemd/system

touch config/includes.chroot/root/startup.sh
cat > config/includes.chroot/root/startup.sh << EOF
#!/bin/bash

set -e

virsh net-start default
virsh net-autostart default
EOF
chmod 775 config/includes.chroot/root/startup.sh

touch config/includes.chroot/etc/systemd/system/startup.service
cat > config/includes.chroot/etc/systemd/system/startup.service << EOF
[Unit]
Description=Amian Startup Service
After=network.target
After=systemd-user-sessions.service
After=network-online.target

[Service]
User=root
Type=forking
ExecStart=/root/startup.sh
TimeoutSec=30
Restart=on-failure
RestartSec=30
StartLimitInterval=350
StartLimitBurst=10

[Install]
WantedBy=multi-user.target
EOF

###### END STARTUP SERVICE ######

#GNOME3 CONFIGURATION
mkdir -p config/includes.chroot/usr/share/amian/images
cp images/amian_wallpaper.png config/includes.chroot/usr/share/amian/images/
mkdir -p config/includes.chroot/home/user/.config/autostart

cat > config/includes.chroot/home/user/.config/myscript.sh << EOF
#!/bin/sh
set -e
gsettings set org.gnome.desktop.background picture-uri file:///usr/share/amian/images/amian_wallpaper.png
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.shell favorite-apps "['google-chrome.desktop','firefox-esr.desktop', 'org.gnome.Nautilus.desktop','org.gnome.Terminal.desktop']"

ret=\$(zenity --entry --title="Amian" --text="Select your keyboard" --entry-text="us" it fr de es ru gb fi pt jp cn hu no ro se --cancel-label cancel --ok-label ok)

gsettings set org.gnome.desktop.input-sources sources "[('xkb', '\$ret')]"

if [ "\$ret" = "it" ]; then
               sudo ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime
            else
               sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
fi

EOF


cat > config/includes.chroot/home/user/.config/autostart/myscript.desktop << EOF
[Desktop Entry]
Name=MyScript
GenericName=Gnome3 Configuration
Comment=this is my custom configuration
Exec=/bin/sh /home/user/.config/myscript.sh
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
EOF

chmod -R 777 config/includes.chroot/home/user/.config

#END GNOME3 CONFIGURATION

###### BEGIN VIM CONFIGURATION ######
touch config/includes.chroot/home/user/.vimrc
echo "set mouse=" > config/includes.chroot/home/user/.vimrc
touch config/includes.chroot/root/.vimrc
echo "set mouse=" > config/includes.chroot/root/.vimrc
###### END VIM CONFIGURATION ######

###### BEGIN AMIAN_DATA INIT ######
mkdir -p config/includes.chroot/AMIAN_DATA
mkdir -p config/includes.chroot/etc/lxc
chmod -R 777 config/includes.chroot/AMIAN_DATA
touch config/includes.chroot/etc/lxc/lxc.conf
cat > config/includes.chroot/etc/lxc/lxc.conf << EOF
lxc.lxcpath=/AMIAN_DATA/
EOF
###### END AMIAN_DATA INIT ######

mkdir -p config/includes.chroot/etc
touch config/includes.chroot/etc/amian_version
echo "Amian $AMIAN_VERSION" > config/includes.chroot/etc/amian_version

####### BEGIN BOOTLOADER #######
mkdir -p config/bootloaders
cp -r /usr/share/live/build/bootloaders/isolinux config/bootloaders/
cp images/amian_isolinux_wallpaper.png config/bootloaders/isolinux/splash.png
rm config/bootloaders/isolinux/splash.svg
echo "" > config/bootloaders/isolinux/install.cfg
####### END BOOTLOADER #######

# Configure WWW
#mkdir -p config/includes.chroot/var/www/html
#touch config/includes.chroot/var/www/html/index.php
#echo "<?php phpinfo(); ?>" > config/includes.chroot/var/www/html/index.php

########### END CONFIG ###########





########### BEGIN BUILD ###########
set -e
lb build noauto "${@}" 2>&1 | tee build.log
########### END BUILD ###########
