#!/bin/bash

AMIAN_VERSION=1.1
AMIAN_BUILD=1.1.0

########### BEGIN CLEAN ###########
set -e
lb clean noauto "${@}"
rm -f config/binary config/bootstrap config/chroot config/common config/source
rm -f build.log
########### END CLEAN ###########


########### BEGIN CONFIG ###########
# --interactive shell \
# --apt-indices false \
# --memtest none \

set -e
lb config noauto \
        --mode debian \
        --distribution buster  \
        --interactive shell \
        --bootloaders syslinux \
        --architectures amd64 \
        --debian-installer live \
        --binary-images iso-hybrid  \
        --archive-areas "main contrib non-free" \
        --bootappend-live "boot=live config locales=en_US.UTF-8 keyboard-layouts=us username=user hostname=amian user-fullname=user@amian" \
        "${@}"

# Configure basic desktop packages
echo task-gnome-desktop > config/package-lists/desktop.list.chroot
echo task-english >> config/package-lists/desktop.list.chroot


# Configure repository packages
#

echo    "git wget macchanger aircrack-ng vim inkscape gimp nmap iptraf vlc whois cryptsetup cryptmount" > config/package-lists/custom.list.chroot

#HOOK in BOOT TIME
mkdir -p config/includes.chroot/lib/live/config
touch config/includes.chroot/lib/live/config/boot_time_hook
echo "#!/bin/sh" > config/includes.chroot/lib/live/config/boot_time_hook
#END HOOK in BOOT TIME


###HOOK
cat > config/hooks/live/amian.hook.chroot << EOF
#!/bin/bash

set -e

cd /root
git clone https://github.com/DoKiNet/GVMI.git
cd GVMI
./gvmi install gvm11

EOF
####END HOOK


#GNOME3 CONFIGURATION
mkdir -p config/includes.chroot/usr/share/amian/images
cp amian_wallpaper.png config/includes.chroot/usr/share/amian/images/
mkdir -p config/includes.chroot/home/user/.config/autostart

cat > config/includes.chroot/home/user/.config/myscript.sh << EOF
#!/bin/sh
set -e
gsettings set org.gnome.desktop.background picture-uri file:///usr/share/amian/images/amian_wallpaper.png
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false

ret=\$(zenity --entry --title="Amian" --text="Select your keyboard" --entry-text="us" it fr de es ru gb fi pt jp cn hu no ro se --cancel-label cancel --ok-label ok)

gsettings set org.gnome.desktop.input-sources sources "[('xkb', '\$ret')]"

if [ "\$ret" = "it" ]; then
               sudo ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime
            else
               sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
fi

EOF


cat > config/includes.chroot/home/user/.config/autostart/myscript.desktop << EOF
[Desktop Entry]
Name=MyScript
GenericName=Gnome3 Configuration
Comment=this is my custom configuration
Exec=/bin/sh /home/user/.config/myscript.sh
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
EOF

chmod -R 777 config/includes.chroot/home/user/.config

#END GNOME3 CONFIGURATION


touch config/includes.chroot/home/user/.vimrc
echo "set mouse=" > config/includes.chroot/home/user/.vimrc

mkdir -p config/includes.chroot/etc
touch config/includes.chroot/etc/amian_version
echo "Amian $AMIAN_VERSION" > config/includes.chroot/etc/amian_version

mkdir -p config/bootloaders
cp -r /usr/share/live/build/bootloaders/isolinux config/bootloaders/
cp amian_isolinux_wallpaper.png config/bootloaders/isolinux/splash.png
rm config/bootloaders/isolinux/splash.svg


# Configure WWW
#mkdir -p config/includes.chroot/var/www/html
#touch config/includes.chroot/var/www/html/index.php
#echo "<?php phpinfo(); ?>" > config/includes.chroot/var/www/html/index.php

########### END CONFIG ###########





########### BEGIN BUILD ###########
set -e
lb build noauto "${@}" 2>&1 | tee build.log
########### END BUILD ###########
