#!/bin/bash

set -e

ARG1=$1
ARG2=$2

check_persistent_partition(){
    AMIAN_PARTITION=$(df | grep "/run/live/medium" | cut -d  ' ' -f 1)
    DEVICE=${AMIAN_PARTITION:0:8}
    PERSISTENT_PARTITION="$DEVICE"2
    MOUNT_POINT="/AMIAN_DATA"
    if [ "$(df --output=source,target | grep $PERSISTENT_PARTITION | sed 's/ //g')" == "$PERSISTENT_PARTITION$MOUNT_POINT" ]; then
        echo "1"
    else
        echo "0"
    fi
}



if [ "$ARG1" == "pp" ] && [ "$ARG2" == "" ]; then
    if [ "$(check_persistent_partition)" == "1" ]; then
        yad --title="Amian  Control  Center" \
            --text="\nPersistent Partition: FOUND" \
            --text-align="center"  \
            --button="Open":0 \
            --button="Create":1 \
            --button="Remove":2 \
            --button="Reset":3 \
            --button="Quit":4 \
            --buttons-layout="center"

    elif [ "$(check_persistent_partition)" == "0" ]; then
        yad --title="Amian  Control  Center" \
            --text="\nPersistent Partition: NOT FOUND" \
            --text-align="center"  \
            --button="Open":0 \
            --button="Create":1 \
            --button="Remove":2 \
            --button="Reset":3 \
            --button="Quit":4 \
            --buttons-layout="center"

    fi
elif [ "$ARG1" == "pp" ] && [ "$ARG2" == "create" ]; then
    echo "insert create_persistent_partition.sh code"
elif [ "$ARG1" == "pp" ] && [ "$ARG2" == "delete" ]; then
    echo "acc pp delete"
elif [ "$ARG1" == "pp" ] && [ "$ARG2" == "reset" ]; then
    echo "acc pp reset"
fi
